name: flutter_shake_vibrate_package
description: A Shake And Vibrate Flutter package.
version: 0.0.2
homepage: https://github.com/GitHubStuff/flutter_shake_vibrate_package

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sensors: ^0.4.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
